config/routes.rb
Rails.application.routes.draw do
  resources :user_sells, only: [] do
    collection do
      get ':user_id', to: 'user_sells#show', as: :user_sells
    end
  end
  resources :extends, only: [] do
    collection do
      get ':customer_id', to: 'extends#show', as: "day_using"
      post ':customer_id', to: 'extends#update'
    end
  end
  resources :service_tables
  resources :user_infos, only: [:index]

  apipie
  root 'homes#index'
  resources :homes do
    collection do
      patch '/ban/:id', to: 'homes#ban', as: 'ban'
      patch '/unban/:id', to: 'homes#unban', as: 'unban'
      get 'update_version', to: "homes#update_version", as: "update_version"
      post 'update_version', to: "homes#update_version_value"
      get 'inform', to: "homes#inform", as: "inform"
      post 'inform', to: "homes#inform_value"
    end
  end
  devise_for :users

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :customers, only: [:create] do
        collection do
          get 'get_current_version', to: 'customers#get_current_version'
          get 'check_is_member', to: 'customers#check_is_member'
          get 'check_is_member_valid', to: 'customers#check_is_member_valid'
          get 'get_inform', to: 'customers#get_inform'
          get 'get_times', to: 'customers#get_times'
        end
      end
      resources :tokens, only: [] do
        collection do
          post 'get_token_facebook', to: 'tokens#get_token_facebook'
        end
      end
      resources :add_friends, only: [] do
        collection do
          get 'invite_friend', to: 'add_friends#invite_friend'
        end
      end
      match '*other', :to => 'base_api#routing_error', via: [:get, :post, :put]
    end
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    @customers_valid = Customer.where("expired_time >= ? AND ban = ?", Time.now, false)
    @customers_invalid = Customer.where("expired_time < ?", Time.now)
    @customers_ban = Customer.where(ban: true)
    if params[:key].present?
      @customers = Customer.where("phone = ? OR mac = ?", params[:key], params[:key])
    end
  end

  def ban
    id = params[:id]
    if home_service.ban_unban(id, true)
      flash[:notice] = "Cấm thành công!"
      redirect_to root_path
    else
      flash[:error] = "Cấm lỗi"
    end
  end

  def unban
   id = params[:id]
    if home_service.ban_unban(id, false)
      flash[:notice] = "Bỏ chặn thành công!"
      redirect_to root_path
    else
      flash[:error] = "Bỏ chặn lỗi"
    end
  end

  def update_version
    @current_version = Version.last
    @current_version = @current_version.present? ? @current_version.version : "v1"
  end

  def update_version_value
    version = params[:version]
    @current_version = Version.last
    if @current_version.present?
      @current_version.update_attributes(version: version)
    else
      Version.create(version: version)
    end
    flash[:notice] = "Update thành công!"
    redirect_to update_version_homes_path
  end

  def inform
    @content = Inform.last
    @content = @content.present? ? @content.content : ""
  end

  def inform_value
    param_content = params[:content]
    content = Inform.last
    if content.present?
      content.update_attributes(content: param_content)
    else
      Inform.create(content: param_content)
    end
    flash[:notice] = "Gửi thông báo thành công!"
    redirect_to inform_homes_path
  end

  private
    def home_service
      @home_service ||= ::HomeService.new
    end

end

app/helpers/homes_helper.rb
module HomesHelper
  def change_second_to_days(t)
    mm, ss = t.divmod(60)
    hh, mm = mm.divmod(60)
    dd, hh = hh.divmod(24)
    "#{dd} days, #{hh} hours, #{mm} minutes"
  end
end

app/views/homes/_menu_1.html.slim
#menu1.tab-pane.fade.in.active
    h3 Thông tin khách hàng còn ngày sử dụng
    .table-responsive
      table.table
        thead
          tr
            th Mã
            th Họ tên
            th Email
            th SĐT
            th Ngày kích hoạt
            th Số ngày sử dụng còn lại
            th Gia hạn
            th Cấm người dùng
        tbody
          - customers_valid.find_each(batch_size: BATCH_SIZE) do |customer_valid|
            tr.active
              td
                = customer_valid.mac
              td
                = customer_valid.full_name
              td
                = customer_valid.email
              td
                = customer_valid.phone
              td
                = customer_valid.created_at
              td
                = change_second_to_days(customer_valid.expired_time - Time.now)

              td
                = link_to 'Gia hạn', day_using_extends_path(customer_valid), class: "btn btn-success btn-sm active"
              td
                = link_to 'Cấm', ban_homes_path(customer_valid.id), class: "btn btn-success btn-sm active", role: "button", method: "patch", data: {confirm: "Are you sure?"}

app/views/homes/_menu_2.html.slim
#menu2.tab-pane.fade
    h3 Thông tin khách hàng đã hết ngày sử dụng
    .table-responsive
      table.table
        thead
          tr
            th Mã
            th Họ tên
            th Email
            th SĐT
            th Ngày kích hoạt
            th Số ngày đã hết hạn đã qua
            th Mua thêm
        tbody
          - customers_invalid.find_each(batch_size: BATCH_SIZE) do |customer_invalid|
            tr
              td
                = customer_invalid.mac
              td
                = customer_invalid.full_name
              td
                = customer_invalid.email
              td
                = customer_invalid.phone
              td
                = customer_invalid.created_at
              td
                = change_second_to_days(Time.now - customer_invalid.expired_time)
              td
                = link_to 'Mua thêm', day_using_extends_path(customer_invalid), class: "btn btn-success btn-sm active"
          doctype XML

app/views/homes/_menu_3.html.slim
#menu3.tab-pane.fade
    .row
      .col-lg-6
        form method="GET"
          .input-group
            input.form-control name="key" placeholder=("Search for...") type="text" /
            span.input-group-btn
              button.btn.btn-default type="submit"  Go!

    .table-responsive
      table.table
        thead
          tr
            th Mã
            th Họ tên
            th Email
            th SĐT
            th Ngày kích hoạt
            th Ngày kết hạn
            th Gia hạn/ trừ ngày
        tbody
          - if params[:key].present?
            - customers.find_each(batch_size: BATCH_SIZE) do |customer|
              tr.success
                td
                  = customer.mac
                td
                  = customer.full_name
                td
                  = customer.email
                td
                  = customer.phone
                td
                  = customer.created_at
                td
                  = customer.expired_time

                td
                  a.btn.btn-success.btn-sm.active href=("") role="button"  Gia hạn/ trừ ngày

app/views/homes/_menu_4.html.slim
#menu4.tab-pane.fade
    h3 Thông tin khách hàng còn ngày sử dụng
    .table-responsive
      table.table
        thead
          tr
            th Mã
            th Họ và tên
            th Số điện thoại
            th Bỏ cấm

        tbody
          - customers_ban.find_each(batch_size: BATCH_SIZE) do |customer_ban|
            tr
              td
                = customer_ban.mac
              td
                = customer_ban.full_name
              td
                = customer_ban.phone
              td
                = link_to 'Bỏ  Cấm', unban_homes_path(customer_ban.id), class: "btn btn-success btn-sm active", role: "button", method: "patch", data: {confirm: "Are you sure?"}

app/views/homes/index.html.slim
h2 Thông tin khách hàng
ul.nav.nav-tabs role="tablist"
  li.active
    a href="#menu1" data-toggle="tab" role="tab"  Còn ngày sử dụng
  li
    a href="#menu2" data-toggle="tab" role="tab"  Hết ngày sử dụng
  li
    a href="#menu3" data-toggle="tab" role="tab"  Tìm kiếm khách hàng
  li
    a href="#menu4" data-toggle="tab" role="tab"  Danh sách khách hàng bị cấm
.tab-content
  = render 'menu_1', customers_valid: @customers_valid
  = render 'menu_2', customers_invalid: @customers_invalid
  = render 'menu_3', customers: @customers
  = render 'menu_4', customers_ban: @customers_ban

app/views/homes/inform.html.slim
.col-sm-7#fm-inform
  h4.green Thông báo
  .widget-box.widget-color-blue
    .widget-header.widget-header-small
    .widget-body
      = form_for inform_homes_path
        .widget-main.no-padding
          textarea.inform-textarea data-iconlibrary="fa" data-provide="markdown" name="content" rows="10"
            = @content
        .widget-toolbox.padding-4.clearfix
          .btn-group.pull-right
            button.btn.btn-sm.btn-purple name="submit" type="submit"
              i.ace-icon.fa.fa-floppy-o.bigger-125
              | Save

app/views/homes/update_version.html.slim
#fm-update-version
  .container
    h3
      | Version hiện tại:
      = @current_version
    h2 Yêu cầu khách hàng update
    = form_for update_version_homes_path, html: {class: "form-inline"}
      .form-group
        label for="version"  Version:
        input#version.form-control name="version" placeholder=("Enter version") required="" type="version" /
      button.btn.btn-default.fm-submit-version name="submit" type="submit"  Submit