config/routes.rb
Rails.application.routes.draw do
  resources :user_sells, only: [] do
    collection do
      get ':user_id', to: 'user_sells#show', as: :user_sells
    end
  end
  resources :extends, only: [] do
    collection do
      get ':customer_id', to: 'extends#show', as: "day_using"
      post ':customer_id', to: 'extends#update'
    end
  end
  resources :service_tables
  resources :user_infos, only: [:index]

  apipie
  root 'homes#index'
  resources :homes do
    collection do
      patch '/ban/:id', to: 'homes#ban', as: 'ban'
      patch '/unban/:id', to: 'homes#unban', as: 'unban'
      get 'update_version', to: "homes#update_version", as: "update_version"
      post 'update_version', to: "homes#update_version_value"
      get 'inform', to: "homes#inform", as: "inform"
      post 'inform', to: "homes#inform_value"
    end
  end
  devise_for :users

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :customers, only: [:create] do
        collection do
          get 'get_current_version', to: 'customers#get_current_version'
          get 'check_is_member', to: 'customers#check_is_member'
          get 'check_is_member_valid', to: 'customers#check_is_member_valid'
          get 'get_inform', to: 'customers#get_inform'
          get 'get_times', to: 'customers#get_times'
        end
      end
      resources :tokens, only: [] do
        collection do
          post 'get_token_facebook', to: 'tokens#get_token_facebook'
        end
      end
      resources :add_friends, only: [] do
        collection do
          get 'invite_friend', to: 'add_friends#invite_friend'
        end
      end
      match '*other', :to => 'base_api#routing_error', via: [:get, :post, :put]
    end
  end
end

app/controllers/service_tables_controller.rb
class ServiceTablesController < ApplicationController
  before_action :set_service_table, only: [:show, :edit, :update, :destroy]

  # GET /service_tables
  # GET /service_tables.json
  def index
    @service_tables = ServiceTable.all
  end

  # GET /service_tables/1
  # GET /service_tables/1.json
  def show
  end

  # GET /service_tables/new
  def new
    @service_table = ServiceTable.new
  end

  # GET /service_tables/1/edit
  def edit
  end

  # POST /service_tables
  # POST /service_tables.json
  def create
    @service_table = ServiceTable.new(service_table_params)

    respond_to do |format|
      if @service_table.save
        format.html { redirect_to service_tables_path, notice: 'Gói dịch vụ mới được tạo!' }
        format.json { render :show, status: :created, location: @service_table }
      else
        format.html { render :new }
        format.json { render json: @service_table.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /service_tables/1
  # PATCH/PUT /service_tables/1.json
  def update
    respond_to do |format|
      if @service_table.update(service_table_params)
        format.html { redirect_to service_tables_path, notice: 'Đã cập nhật thành công!' }
        format.json { render :show, status: :ok, location: @service_table }
      else
        format.html { render :edit }
        format.json { render json: @service_table.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /service_tables/1
  # DELETE /service_tables/1.json
  def destroy
    @service_table.destroy
    respond_to do |format|
      format.html { redirect_to service_tables_url, notice: 'Đã xóa thành công!' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service_table
      @service_table = ServiceTable.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_table_params
      params.require(:service_table).permit(:price, :day_of_use)
    end
end

app/helpers/service_tables_helper.rb
module ServiceTablesHelper
end

app/views/service_tables/_form.html.slim
= form_for(@service_table) do |f|
  - if @service_table.errors.any?
    #error_explanation
      h2
        = pluralize(@service_table.errors.count, "error")
        | prohibited this service_table from being saved:
      ul
        - @service_table.errors.full_messages.each do |message|
          li= message
  .field
    = f.label :price
    br
    = f.number_field :price
  .field
    = f.label :day_of_use
    br
    = f.number_field :day_of_use
  .actions
    = f.submit "#{params[:action] == 'new' ? 'Tạo mới' : 'Cập nhật'}", class: "btn btn-success"

app/views/service_tables/edit.html.slim
h1 Chỉnh sửa gói dịch vụ
= render 'form'
= link_to 'Back', service_tables_path

app/views/service_tables/index.html.slim
h1 Bảng giá dịch vụ
.table-responsive
  table.table
    thead
      tr
        th Giá
        th Ngày sử dụng
        th colspan="3"
    tbody
      - @service_tables.each do |service_table|
        tr
          td= service_table.price
          td= service_table.day_of_use
          td= link_to 'Edit', edit_service_table_path(service_table)
          td= link_to 'Destroy', service_table, method: :delete, data: {confirm: 'Are you sure?'}
br
= link_to 'Tạo gói mới', new_service_table_path, class: "btn btn-success"

app/views/service_tables/new.html.slim
h1 Tạo gói dịch vụ mới
= render 'form'
= link_to 'Back', service_tables_path