config/routes.rb
Rails.application.routes.draw do
  resources :user_sells, only: [] do
    collection do
      get ':user_id', to: 'user_sells#show', as: :user_sells
    end
  end
  resources :extends, only: [] do
    collection do
      get ':customer_id', to: 'extends#show', as: "day_using"
      post ':customer_id', to: 'extends#update'
    end
  end
  resources :service_tables
  resources :user_infos, only: [:index]

  apipie
  root 'homes#index'
  resources :homes do
    collection do
      patch '/ban/:id', to: 'homes#ban', as: 'ban'
      patch '/unban/:id', to: 'homes#unban', as: 'unban'
      get 'update_version', to: "homes#update_version", as: "update_version"
      post 'update_version', to: "homes#update_version_value"
      get 'inform', to: "homes#inform", as: "inform"
      post 'inform', to: "homes#inform_value"
    end
  end
  devise_for :users

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :customers, only: [:create] do
        collection do
          get 'get_current_version', to: 'customers#get_current_version'
          get 'check_is_member', to: 'customers#check_is_member'
          get 'check_is_member_valid', to: 'customers#check_is_member_valid'
          get 'get_inform', to: 'customers#get_inform'
          get 'get_times', to: 'customers#get_times'
        end
      end
      resources :tokens, only: [] do
        collection do
          post 'get_token_facebook', to: 'tokens#get_token_facebook'
        end
      end
      resources :add_friends, only: [] do
        collection do
          get 'invite_friend', to: 'add_friends#invite_friend'
        end
      end
      match '*other', :to => 'base_api#routing_error', via: [:get, :post, :put]
    end
  end
end

app/views/layouts/_alert.html.slim
- flash.each do |key, value|
  - key = "success" if key == "notice"
  - key = "danger" if key == "error" || key == "alert"
  div class="alert alert-#{key}" id="ld-alert"
    button.close aria-label="Close" data-dismiss="alert" type="button"
      span aria-hidden="true"  &times;
    = value

app/views/layouts/_header.html.slim
nav.navbar.navbar-inverse
  .container-fluid
    .navbar-header
      = link_to "Ultra Facebook", root_path, class: "navbar-brand"
    div
      ul.nav.navbar-nav
        li
          = link_to "Home", homes_path
        li
          = link_to 'Thông báo', inform_homes_path
        li
          = link_to 'Thông tin nhân viên', user_infos_path
        li
          = link_to 'Update hệ thống', update_version_homes_path
        li
          = link_to 'Bảng giá dịch vụ', service_tables_path
      ul.nav.navbar-nav style=("float: right;")
        li
          = link_to 'Thoát', destroy_user_session_path, method: "DELETE"
      ul.nav.navbar-nav style=("float: right;")
        li
          a
            = I18n.t("name", first_name: current_user.first_name, last_name:  current_user.last_name)

app/views/layouts/_login_signup.html.slim
.main-container
  .main-content
    .row
      .col-sm-10.col-sm-offset-1
        .login-container
          .center
            h1
              i.ace-icon.fa.fa-leaf.green
              span.red Digital
              span#id-text2.white Marketing
            h4#id-company-text.blue ULTRAFACEBOOK
          .space-6
          .position-relative
            = yield

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title Facebookmarketing
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  - if params[:controller]=='devise/sessions' || params[:controller] =='devise/registrations'
    body.login-layout
      = render 'layouts/login_signup'
  - else
    body
      = render 'layouts/header'
      .container
        = render 'layouts/alert'
        = yield